import  {ClerkProvider} from "@clerk/nextjs"
import { Anek_Bangla} from "next/font/google";
import "./globals.css";
import Header from "./components/Header"

const banglaFont=Anek_Bangla({weight:["400"],subsets:["bengali"]});

export const metadata = {
  title: "বই সমূহ",
  description: "Generated by create mazaharul islam ",
};

export default function RootLayout({ children }) {
  return (
<ClerkProvider>


    <html lang="en">
      <body
        className={`${banglaFont.className} antialiased bg-stone-100`}
      >
        <Header/>
        <h1>Welcome</h1>
        {children}
      </body>
    </html>
    </ClerkProvider>
  );
}
